model_type = 'ae'

train_param = dict(
    exp_name='markcleaner_train',
    lr=2e-4,
    gan_lr=2e-4,
    d_zero_step=1,
    d_warmup_step=1,
    epoch=800,
    milestones=[750, 780],
    resume=False,
    model_path=None,
    mask=True,
    enable_freq_mask=True,
    freq_mask_max_prob=0.6,
    freq_mask_warmup_steps=200000,
    wandb=False,
    wandb_proj='markcleaner',
    wandb_name='markcleaner_train',
    tensorboard_dir='runs',
    log_step=10,
    save_step=5000,
    sample_step=2000,
    sample_dir='samples',
    output_dir='outputs/checkpoints',
    use_multi_mask_ratio=True,
    ratio_interp=200,
    min_ratio=0.2,
    max_ratio=0.6,
    loss_type=dict(
        reconstruction='full_l1', gan='hinge', gan_iter_step=1,
        gan_gradient_penalty=False, r1_weight=10,
        perceptual_loss='lpips', partial_scale=0, recons_scale=1,
        perceptual_scale=3, gan_scale=0.3, dino_pred_scale=1,
        freq_loss=True, freq_scale=1, freq_scale_start=0.0,
        freq_scale_warmup_epochs=100, fft_max_radius=128,
        fft_min_radius=60, use_wavelet_hh=True, use_multi_scale=True,
        freq_scales=[1, 2, 4],
    ),
)

data_param = dict(
    use_mfm_format=True,
    path='/path/to/train_pairs',
    is_train=True,
    shuffle=True,
    num_workers=4,
    bs=16,
    use_txt_files=True,
    img_size=256,
    filter_type='mfm',
    mask_radius1=16,
    mask_radius2=999,
    sample_ratio=0.5,
    min_crop_scale=0.0,
    mask_type=[2, 4],
)

model_param = dict(
    image_size=(256, 256), patch_size=(16, 16), hidden_dim=12,
    use_dino_cls=True, use_dino_pred_loss=True, gaussian_per_patch=324,
    encoder_type='resnet',
    encoder_args=dict(use_skip=True, norm_layer='gn', up_norm_layer='gn'),
    overlap=True, overlap_pad=1, condition_type='direct',
)
